apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello-pod
  name: hello-pod
spec:
  containers:
  - image: nginx
    name: hello-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure
status: {}
